classes: {
  block: {...${carbon.node}; width: 192; style: {fill: ${color.surface}; stroke: ${color.outline}}}
  group: {...${carbon.container}; style: {fill: ${color.surface-subtle}; stroke: ${color.outline}}}
  link: {...${carbon.line}; style.stroke: ${color.line}}
}
