classes: {
  component: {}
  actor: {shape: person}
  system: {shape: oval}
  node: {style.border-radius: 8}
  junction: {shape: circle; width: 12; height: 12; label: ""}
  location: {style.border-radius: 8}
  zone: {style.stroke-dash: 2}
  subsystem: {}
  connection: {}
  async: {style.stroke-dash: 4}
}
