classes: {
  process: {shape: rectangle}
  start: {shape: oval}
  end: {shape: oval}
  decision: {shape: diamond}
  io: {shape: parallelogram}
  subprocess: {shape: rectangle; style.double-border: true}
  store: {shape: cylinder}
  note: {shape: page}
  group: {}
  flow: {}
  optional: {style.stroke-dash: 4}
}
