vars: { inkline: { diagram: block; design_system: carbon } }

grid-columns: 3
grid-gap: 16
frontend: Frontend
api: API
auth: Auth
services: Services {
  grid-columns: 2
  orders: Orders
  billing: Billing
}
queue: Queue
db: Database {class: data}
