vars: { inkline: { diagram: quadrant; design_system: carbon } }

title: Reach and engagement of campaigns
x: Reach →
y: Engagement →
q1: We should expand {
  campaign_a: Campaign A
  campaign_f: Campaign F
}
q2: Need to promote {
  campaign_b: Campaign B
}
q3: Re-evaluate {
  campaign_c: Campaign C
}
q4: May be improved {
  campaign_d: Campaign D
  campaign_e: Campaign E
}
