vars: { inkline: { diagram: treeview; design_system: carbon } }

second_floor: Second floor {
  classification: Classification
  geography: Geography
  location: Location {
    tri_building: triBuilding
    tri_floor: triFloor
    tri_space: triSpace {
      is_parent_of: Is Parent Of
      has: has {
        as11: 02-AS11 {
          tri_people: triPeople {
            profile: My Profile
          }
          tri_routing: triRouting
        }
        bm26: 02-BM26
        bp04: 02-BP04
      }
    }
  }
  organization: Organization
  system: System
}
