#!/bin/sh
# Regenerates THIRD_PARTY_NOTICES.md: the licences of everything inkline
# redistributes. Run after changing go.mod, the bundled fonts or icons, or the
# docs site's theme.
set -eu
cd "$(dirname "$0")/.."

out=THIRD_PARTY_NOTICES.md
modcache=$(go env GOMODCACHE)

# Module paths are stored case-encoded in the module cache: A -> !a.
cachepath() { printf '%s' "$1" | sed 's/[A-Z]/!&/g' | tr 'A-Z' 'a-z'; }

licence() {
  # The first licence-like file in a directory, verbatim.
  f=$(ls "$1" 2>/dev/null | grep -iE '^(licen[cs]e|copying)' | head -1)
  if [ -n "$f" ]; then
    printf '```text\n'
    cat "$1/$f"
    printf '\n```\n'
  else
    printf '_No licence file found in %s._\n' "$1"
  fi
}

{
cat <<'EOF'
# Third-party notices

inkline itself is licensed under the Apache License 2.0 (see `LICENSE` and
`NOTICE`). It redistributes the software and assets below. This file lists each
with its licence text, as the licences require. It is generated by
`scripts/notices.sh`; do not edit it by hand.

inkline is not affiliated with or endorsed by IBM, Amazon or Microsoft. IBM, IBM
Plex, Carbon, Amazon, AWS, Cloudscape, Microsoft, Fluent, Segoe and Selawik are
used only to name the typefaces and design systems the `carbon`, `cloudscape`
and `fluent` kits follow.

Two components are under file-level copyleft licences: D2 (Mozilla Public
License 2.0) and elk-go (Eclipse Public License 2.0). inkline uses them unmodified;
their source, at the versions listed below, is available from
<https://github.com/d2lang/d2> and <https://github.com/d2lang/elk-go>. These
licences cover those components' files only and place no terms on inkline's own
code.

## Bundled assets

These files are in the repository and embedded in the inkline binary.

### IBM Plex Sans

`kits/carbon/fonts/*.ttf`, unmodified, from
<https://github.com/IBM/plex>. Licensed under the SIL Open Font License 1.1.
Rendered SVGs embed subsets of these fonts, which the licence permits.

EOF
cat kits/carbon/fonts/LICENSE.txt | { printf '```text\n'; cat; printf '\n```\n'; }

cat <<'EOF'

### Carbon icons

`kits/carbon/icons/user.svg` is the `user` icon from
[@carbon/icons](https://github.com/carbon-design-system/carbon/tree/main/packages/icons),
Copyright IBM Corp. Licensed under the Apache License 2.0.

EOF
curl -sfL https://www.apache.org/licenses/LICENSE-2.0.txt | { printf '```text\n'; cat; printf '\n```\n'; }

cat <<'EOF'

### Open Sans

`kits/cloudscape/fonts/*.ttf`, unmodified, from
<https://github.com/googlefonts/opensans>. Licensed under the SIL Open Font
License 1.1.

EOF
cat kits/cloudscape/fonts/OFL.txt | { printf '```text\n'; cat; printf '\n```\n'; }

cat <<'EOF'

### Cloudscape design tokens and icon

The colour values in `kits/cloudscape/tokens-light.d2` and `tokens-dark.d2`
come from
[@cloudscape-design/design-tokens](https://www.npmjs.com/package/@cloudscape-design/design-tokens).
`kits/cloudscape/icons/user-profile.svg` is Cloudscape's `user-profile` icon,
unmodified, from
[cloudscape-design/components](https://github.com/cloudscape-design/components).
The avatar colours come from its chat components' Avatar tokens. Both are
licensed under the Apache License 2.0 (text
above) with this notice:

```text
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
```

The domain and group colours in the cloudscape kit follow AWS's architecture
diagram conventions (the service categories of its icons, and its groups). No AWS Architecture Icons are included: they are not openly
licensed, so users download them from AWS.

### Selawik

`kits/fluent/fonts/*.ttf`, unmodified, from
<https://github.com/microsoft/Selawik>: Microsoft's open-source substitute for
Segoe UI, which is not redistributable. Licensed under the SIL Open Font
License 1.1, with Reserved Font Name Selawik.

EOF
cat kits/fluent/fonts/LICENSE.txt | { printf '```text\n'; cat; printf '\n```\n'; }

cat <<'EOF'

### Fluent design tokens

The colour values in `kits/fluent/tokens-light.d2` and `tokens-dark.d2` come
from
[@fluentui/react-theme](https://www.npmjs.com/package/@fluentui/react-theme)
and [@fluentui/tokens](https://www.npmjs.com/package/@fluentui/tokens),
licensed under the MIT License. The licence's note about fonts and icons
covers Segoe UI and Fluent's hosted assets, none of which inkline includes.

EOF
cat kits/fluent/LICENSE-tokens.txt | { printf '```text\n'; cat; printf '\n```\n'; }

cat <<'EOF'

### Fluent UI System Icons

`kits/fluent/icons/person.svg` is the `ic_fluent_person_24_regular` icon,
unmodified, from
[microsoft/fluentui-system-icons](https://github.com/microsoft/fluentui-system-icons),
licensed under the MIT License:

EOF
cat kits/fluent/icons/LICENSE.txt | { printf '```text\n'; cat; printf '\n```\n'; }

cat <<'EOF'

### Carbon colour tokens

The `carbon` design system's colour values follow the
[Carbon Design System](https://carbondesignsystem.com/) palette, Copyright IBM
Corp., licensed under the Apache License 2.0 (text above).

## Go modules

These are compiled into the inkline binary.

EOF
go list -deps -f '{{with .Module}}{{if not .Main}}{{.Path}} {{.Version}}{{end}}{{end}}' ./cmd/inkline |
  sort -u |
  while read -r path version; do
    printf '### %s %s\n\n' "$path" "$version"
    licence "$modcache/$(cachepath "$path")@$version"
    printf '\n'
  done

d2=$(go list -m -f '{{.Dir}}' github.com/d2lang/d2)
cat <<'EOF'
## D2's own third-party notices

D2 embeds fonts, icons and code from other projects, and inkline embeds D2. D2's
notices for those follow, verbatim.

EOF
printf '```text\n'
cat "$d2/THIRD_PARTY_NOTICES.txt"
printf '\n```\n'

cat <<'EOF'

## Docs site

The site in `site/` is built with the Hextra theme, whose CSS and JavaScript
ship in the built site. The site loads IBM Plex from Google Fonts rather than
redistributing it.

EOF
hextra=$(cd site && hugo mod graph 2>/dev/null | grep -o 'github.com/imfing/hextra@v[^ ]*' | head -1)
printf '### %s\n\n' "$hextra"
licence "$(find "$HOME/Library/Caches/hugo_cache" "${HUGO_CACHEDIR:-/nonexistent}" -maxdepth 8 -type d -name "$(basename "$hextra")" 2>/dev/null | head -1)"
} > "$out"

echo "wrote $out ($(wc -l < "$out" | tr -d ' ') lines)"
