# Colour values from @cloudscape-design/design-tokens 3.0.113 (visual refresh),
# Apache License 2.0; see THIRD_PARTY_NOTICES.md.
vars: {
  color: {
    canvas: "#161d26"
    surface: "#161d26"
    surface-subtle: "#1b232d"
    text: "#c6c6cd"
    text-muted: "#c6c6cd"
    heading: "#ebebf0"
    outline: "#656871"
    divider: "#424650"
    card-border: "#424650"
    line: "#c6c6cd"
    on-strong: "#0f141a"
    success: "#2bb534"
    success-subtle: "#001401"
    error: "#ff7a7a"
    warning: "#fbd332"
    info: "#42b4ff"
    avatar: "#424650"
    on-avatar: "#ffffff"
    strong: "#e9ebed"
    compute: "#ed7100"
    storage: "#7aa116"
    data: "#c925d1"
    network: "#a47bff"
    security: "#f0617a"
    application: "#f0509b"
    observability: "#f0509b"
    devops: "#c925d1"
    backend: "#9aa4b1"
    aws-cloud: "#e9ebed"
    region: "#00a4a6"
    availability-zone: "#00a4a6"
    vpc: "#a47bff"
    public-subnet: "#8fbb1c"
    public-subnet-fill: "#1a2410"
    private-subnet: "#00b8ba"
    private-subnet-fill: "#0b2226"
    security-group: "#f0617a"
    auto-scaling-group: "#ff8a2a"
    data-center: "#9aa4b1"
  }
  d2-config: {
    theme-overrides: {
      N1: "#c6c6cd"
      N2: "#c6c6cd"
      N3: "#c6c6cd"
      N4: "#656871"
      N5: "#424650"
      N6: "#424650"
      N7: "#161d26"
      B1: "#c6c6cd"
      B2: "#656871"
      B3: "#656871"
      B4: "#424650"
      B5: "#1b232d"
      B6: "#161d26"
      AA2: "#e9ebed"
      AA4: "#1b232d"
      AA5: "#1b232d"
      AB4: "#1b232d"
      AB5: "#1b232d"
    }
  }
}
