# Colour values from @cloudscape-design/design-tokens 3.0.113 (visual refresh),
# Apache License 2.0; see THIRD_PARTY_NOTICES.md.
vars: {
  color: {
    canvas: "#ffffff"
    surface: "#ffffff"
    surface-subtle: "#f6f6f9"
    text: "#0f141a"
    text-muted: "#424650"
    heading: "#0f141a"
    outline: "#8c8c94"
    divider: "#c6c6cd"
    card-border: "#c6c6cd"
    line: "#424650"
    on-strong: "#ffffff"
    success: "#00802f"
    success-subtle: "#effff1"
    error: "#db0000"
    warning: "#855900"
    info: "#006ce0"
    avatar: "#424650"
    on-avatar: "#ffffff"
    strong: "#232f3e"
    compute: "#ed7100"
    storage: "#7aa116"
    data: "#c925d1"
    network: "#8c4fff"
    security: "#dd344c"
    application: "#e7157b"
    observability: "#e7157b"
    devops: "#c925d1"
    backend: "#7d8998"
    aws-cloud: "#232f3e"
    region: "#00a4a6"
    availability-zone: "#00a4a6"
    vpc: "#8c4fff"
    public-subnet: "#7aa116"
    public-subnet-fill: "#f2f6e8"
    private-subnet: "#00a4a6"
    private-subnet-fill: "#e6f6f7"
    security-group: "#dd344c"
    auto-scaling-group: "#ed7100"
    data-center: "#7d8998"
  }
  d2-config: {
    theme-overrides: {
      N1: "#0f141a"
      N2: "#424650"
      N3: "#424650"
      N4: "#8c8c94"
      N5: "#c6c6cd"
      N6: "#c6c6cd"
      N7: "#ffffff"
      B1: "#424650"
      B2: "#8c8c94"
      B3: "#8c8c94"
      B4: "#c6c6cd"
      B5: "#f6f6f9"
      B6: "#ffffff"
      AA2: "#232f3e"
      AA4: "#f6f6f9"
      AA5: "#f6f6f9"
      AB4: "#f6f6f9"
      AB5: "#f6f6f9"
    }
  }
}
